services:
  - type: web
    name: sistemapos
    env: python
    plan: free
    region: oregon
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
    startCommand: gunicorn SistemaPOS.wsgi:application
    postDeployCommand: python manage.py migrate
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.2
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_ADMIN_USERNAME
        value: admin
      - key: DJANGO_ADMIN_EMAIL
        value: admin@example.com
      - key: DJANGO_ADMIN_PASSWORD
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: sistemapos-db
          property: connectionString
      - key: DJANGO_SECURE_PROXY_SSL_HEADER
        value: "HTTP_X_FORWARDED_PROTO,https"
      - key: WHITENOISE_KEEP_ONLY_HASHED_FILES
        value: "True"

# Postgres database definition (Free tier)
databases:
  - name: sistemapos-db
    plan: free
    region: oregon
